---
apiVersion: v1
kind: Pod
metadata:
  name: mynginx
  labels:
    app: mynginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mynginx-svc-np
spec:
  type: NodePort
  selector:
    app: mynginx
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31008
